---
- name: Install libraries with homebrew
  homebrew: name={{ item }} state=present
  tags: brew
  with_items:
    - git
    - wget
    - chruby
    - direnv
    - ruby-install
    - wrk
    - tree
    - httpie
