if has('vim_starting')
 set nocompatible               " Be iMproved

 " Required:
 set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'flazz/vim-colorschemes'


" NeoBundle 'Shougo/neosnippet.vim'
" NeoBundle 'Shougo/neosnippet-snippets'
" NeoBundle 'tpope/vim-fugitive'
" NeoBundle 'kien/ctrlp.vim'


" You can specify revision/branch/tag.
" NeoBundle 'Shougo/vimshell', { 'rev' : '3787e5' }

call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

" ----------------------------------------------"
" MacVim modifications (color, shortcuts, etc.. "
" ----------------------------------------------"
let macvim_skip_colorscheme=1
syntax enable
set background=dark
colorscheme solarized
highlight SignColumn guibg=#272822
highlight SyntasticErrorLine guifg=white guibg=#6e3232
highlight ExtraWhitespace ctermbg=red guibg=#CCCCCC

"CtrlP
let g:ctrlp_working_path_mode=2
" Open ctrlp with cmd+p
let g:ctrlp_map = '<D-p>'
